### ISSUE TITLE
Add LOOBin for launchctl

### ISSUE THREAD

**Issue by infosecB** [infosecB/LOOBins#16]

**Comment by caffeinatedJAC** [comment]
Will claim this one @infosecB!

**Comment by infosecB** [comment]
@caffeinatedJAC still planning on tackling this one?

**Comment by caffeinatedJAC** [comment]
Hey @infosecB yeah nearly done with it will have it added soon.

**Comment by caffeinatedJAC** [comment]
@infosecB was following the contribution guide and got an error when I tried to push my branch I get an access denied. 

![Capture](https://github.com/infosecB/LOOBins/assets/131266155/81f0edb5-6a26-41cc-ba1f-03741b436e31)

**Comment by infosecB** [comment]
@caffeinatedJAC Did you fork the repo first? Looks like you're trying to push directly to my repo. Fork it -> add LOOBin to forked repo -> create pull request from your forked repo back to mine.

Can also drop YAML here and I'll get it added.

**Comment by caffeinatedJAC** [comment]
Sorry about that @infosecB! Figured it out and got it set up properly.
