### ISSUE TITLE
Add LOOBin for curl

### ISSUE THREAD

**Issue by yo-yo-yo-jbo** [infosecB/LOOBins#37]
### LOOBin description

Can probably just copy-paste from Windows \ Linux LOLBINs FWIW

**Comment by infosecB** [comment]
@yo-yo-yo-jbo before you get too far, the plan is to exclude any binaries that overlap with ones already included in the GTFOBins project.

**Comment by infosecB** [comment]
Dropping, this one's covered in GTFObins.
