### ISSUE TITLE
Add LOOBin for lsbom

### ISSUE THREAD

**Issue by yo-yo-yo-jbo** [infosecB/LOOBins#42]

**Comment by infosecB** [comment]
@yo-yo-yo-jbo - I have searched high and low to try to understand how this particular binary is (or might) be used by threat actors. Did you have anything specific in mind for lsbom?

**Comment by yo-yo-yo-jbo** [comment]
I think getting the BOM from PKGs could be useful in some cases (e.g. lsbom ./com.example.apple-samplecode.InstallTest.pkg/Bom) - https://apple.stackexchange.com/questions/125220/how-do-i-know-what-files-are-installed-by-an-installer-program

**Comment by infosecB** [comment]
I'll take a closer look, thanks for the guidance @yo-yo-yo-jbo
