### ISSUE TITLE
Add LOOBin for hdiutil

### ISSUE THREAD

**Issue by yo-yo-yo-jbo** [infosecB/LOOBins#51]

**Comment by MarkMorow** [comment]
@infosecB could I take this one?

**Comment by infosecB** [comment]
It's all yours @MarkMorow

**Comment by infosecB** [comment]
@MarkMorow still planning on authoring this one?

**Comment by MarkMorow** [comment]
@infosecB Yep. Will hopefully knock this out next week.

**Comment by MarkMorow** [comment]
@infosecB Just submitted the PR. I could probably spend more time digging into this for other ways it can be use but this should be the basics.
