### ISSUE TITLE
Add LOOBin for kextstat

### ISSUE THREAD

**Issue by yo-yo-yo-jbo** [infosecB/LOOBins#53]

**Comment by MarkMorow** [comment]
@infosecB I can try taking on this one in the next few weeks.

**Comment by infosecB** [comment]
Awesome, thanks @MarkMorow!

**Comment by MarkMorow** [comment]
@infosecB  getting back to this. (https://github.com/infosecB/LOOBins/pull/147). I think we probably need to add kmutil to the list as kextstat is deprecated.

**Comment by infosecB** [comment]
Makes sense, thanks @MarkMorow !
