### ISSUE TITLE
Add LOOBin for security

### ISSUE THREAD

**Issue by Pratik-987** [infosecB/LOOBins#75]
### LOOBin description

name: security
author: Pratik Jeware (@Pratik-987)
short_description: Dumping a keychain Content via Security command.
full_description: security is a command-line utility included in macOS that allows users to dump keychain. 
Keychains are the built-in way for macOS to keep track of users' passwords and credentials for many services and features, including Wi-Fi and website passwords, secure notes, certificates, and Kerberos.
created: 2023-04-23
example_use_cases:
  - name: Use security to dump keychain passwords from logon.keychain which contains you account information.
    description: This command will dump keychain passwords from login.keychain
    code: sudo security dump-keychain -d login.keychain
    tactics:    
      - Credentials from Password Stores  
      - Credential Access  
    tags:          
      - bash  
paths:
  - /usr/bin/security
detections:
  - name: Command Line Argument Detection (path contains bin/security AND cmdline contains security dump )  
    url: n/a
resources:
  - name: 'MITRE ATT&CK'  
    url: https://attack.mitre.org/techniques/T1555/001/

**Comment by infosecB** [comment]
@Pratik-987 thanks for putting this together. Would you like to open a formal pull request for this one? If not, I can take care of it.

**Comment by Pratik-987** [comment]
You can pull request

**Comment by infosecB** [comment]
Closing issue, duplicate of #60.

**Comment by infosecB** [comment]
@Pratik-987 thank you for helping out! I added and merged the LOOBin for security:
https://github.com/infosecB/LOOBins/pull/82
